-- population SQL products

INSERT INTO products_cfa VALUES (0, 'chicken_sandwich', 4.85);

INSERT INTO products_cfa VALUES (1, 'deluxe_sandwich', 5.55);

INSERT INTO products_cfa VALUES (2, 'spicy_sandwich', 5.25);

INSERT INTO products_cfa VALUES (3, 'spicy_deluxe', 5.95);

INSERT INTO products_cfa VALUES (4, 'chicken_biscuit', 3.55);

INSERT INTO products_cfa VALUES (5, 'spicy_biscuit', 4.49);

INSERT INTO products_cfa VALUES (6, 'hash_browns', 1.55);

INSERT INTO products_cfa VALUES (7, 'five_nuggets', 3.05);

INSERT INTO products_cfa VALUES (8, 'eight_nuggets', 4.85);

INSERT INTO products_cfa VALUES (9, 'twelve_nuggets', 6.85);

INSERT INTO products_cfa VALUES (10, 'cobb_salad', 9.49);

INSERT INTO products_cfa VALUES (11, 'market_salad', 9.69);

INSERT INTO products_cfa VALUES (12, 'waffle_fries', 2.35);

INSERT INTO products_cfa VALUES (13, 'side_salad', 2.35);

INSERT INTO products_cfa VALUES (14, 'waffle_chips', 2.09);

INSERT INTO products_cfa VALUES (15, 'frosted_lemonade', 4.35);

INSERT INTO products_cfa VALUES (16, 'frosted_coffee', 4.35);

INSERT INTO products_cfa VALUES (17, 'chocolate_cookie', 1.65);

INSERT INTO products_cfa VALUES (18, 'lemonade', 2.55);

INSERT INTO products_cfa VALUES (19, 'ice_tea', 2.19);

INSERT INTO products_cfa VALUES (20, 'sweet_tea', 2.19);

INSERT INTO products_cfa VALUES (21, 'water_bottle', 2.25);

INSERT INTO products_cfa VALUES (22, 'cfa_sauce', 0);

INSERT INTO products_cfa VALUES (23, 'ranch_sauce', 0);

INSERT INTO products_cfa VALUES (24, 'honey_mustard', 0);